from PyQt5 import QtCore, QtGui, QtWidgets
from setupFile import Ui_MainWindow2
from MainApp import Ui_MainWindow3



class Ui_MainWindow(object):
    def openSetup(self):
        self.window1 = QtWidgets.QMainWindow()
        self.ui1 = Ui_MainWindow2()
        self.ui1.setupUi(self.window1)
        self.window1.show()

    def openMainApp(self):
        self.window3 = QtWidgets.QMainWindow()
        self.ui3 = Ui_MainWindow3()
        self.ui3.setupUi(self.window3)
        self.window3.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fileNew = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openSetup())
        self.fileNew.setGeometry(QtCore.QRect(30, 410, 151, 51))
        font = QtGui.QFont()
        font.setFamily("White Rabbit")
        font.setPointSize(11)
        self.fileNew.setFont(font)
        self.fileNew.setObjectName("fileNew")
        self.openFile = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openMainApp())
        self.openFile.setGeometry(QtCore.QRect(210, 410, 151, 51))
        font = QtGui.QFont()
        font.setFamily("White Rabbit")
        font.setPointSize(11)
        self.openFile.setFont(font)
        self.openFile.setObjectName("openFile")
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(570, 410, 121, 51))
        font = QtGui.QFont()
        font.setFamily("White Rabbit")
        font.setPointSize(11)
        self.settings.setFont(font)
        self.settings.setObjectName("settings")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 10, 661, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionCustimization = QtWidgets.QAction(MainWindow)
        self.actionCustimization.setObjectName("actionCustimization")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionNew_File = QtWidgets.QAction(MainWindow)
        self.actionNew_File.setObjectName("actionNew_File")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTool.addAction(self.actionSettings)
        self.menuTool.addAction(self.actionCustimization)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileNew.setText(_translate("MainWindow", "New File"))
        self.openFile.setText(_translate("MainWindow", "Open File"))
        self.settings.setText(_translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTool.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionCustimization.setText(_translate("MainWindow", "Customization"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionNew_File.setText(_translate("MainWindow", "New File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
